[package]
name = "dotr"
version = "0.5.6"
edition = "2024"

[dependencies]
toml = "0.9.8"
walkdir = "2.5.0"

[dependencies.clap]
version = "4.5.51"
features = ["derive"]

[dependencies.serde]
version = "1.0.228"
features = ["derive"]
